### ISSUE TITLE
pre-processed data

### ISSUE THREAD

**Issue by flybiubiu** [ywyue/FiT3D#1]
Could you put in some of the pre-processed data?Thx

**Comment by ywyue** [comment]
Hi @flybiubiu, thanks for your interest in our work. According to ScanNet++ Terms of Use, we are not allowed to release the pre-processed data itself but only the preprocessing scripts.

Please submit application and download the data from ScanNet++ [official website](https://kaldir.vc.in.tum.de/scannetpp/) (they usually reply fast), then follow our [instructions](https://github.com/ywyue/FiT3D/tree/main/scannetpp_preprocess) to preprocess the data. If you meet any issues when preprocessing the data, feel free to let me know. Thank you.

**Comment by flybiubiu** [comment]
Thx auther!

**Comment by ywyue** [comment]
Update regarding sharing pre-processed data for people who might be interested: 

*Each new user needs to submit application to request access to ScanNet++ from its official website [official website](https://kaldir.vc.in.tum.de/scannetpp/).* According to the Terms of Use of ScanNet++, we can only share the preprocessed data with people who have also signed the Terms of Use and been granted access to ScanNet++. After you submit your application and get approved from the ScanNet++ team, you can forward the approval email to yuayue@ethz.ch and then we will share our preprocessed data with you directly.
