### ISSUE TITLE
Open-word ability for Segmentation task

### ISSUE THREAD

**Issue by lianhh1212** [ywyue/FiT3D#11]
Thanks for your great work！Can I apply to other custom datasets without training for segmentation task？

**Comment by ywyue** [comment]
Hi @lianhh1212, thank you for your kind words!

Sorry for the late response. For open-world (vocabulary) segmentation, maybe you could try the fine-tuned CLIP model. However, it was only finetuned on ScanNet++ so it may not work well on out-of-distribution datasets.
