### ISSUE TITLE
关于应用于单目深度估计

### ISSUE THREAD

**Issue by chaoying0115** [ywyue/FiT3D#3]
您好，感谢您团队的出色工作。我对于论文中应用至深度估计有提升非常感兴趣，因为我主要做深度估计方面研究。想请问具体是将哪部分引入到深度估计当中，大致是如何操作？非常期待您的回复和指导，谢谢！

**Comment by ywyue** [comment]
Hi @chaoying0115 , thanks for your interest in our work!

We first lift features from 2D foundation models to 3D Gaussians. Then we use rendered features from 3D Gaussians to fine-tune 2D foundation models back. Depth estimation and semantic segmentation are just two downstream tasks we use to demonstrate the benefits of 3D-aware fine-tuning. Regarding depth estimation, we simply add a linear probing on top of the fine-tuned features. 

Please see Sec. 3.3 for more details.

Note as we only fine-tuned the model on ScanNet++ (an indoor dataset), we found we still need to original 2D features to keep their generalization ability.

**Comment by chaoying0115** [comment]
您好，感谢您的回复。我的单目估计模型是在KITTI数据集上训练，您提到您的微调模型是在ScanNet++上进行，那也就是说我没办法应用到我的模型上是吗？




ccying
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ywyue/FiT3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ywyue/FiT3D] 关于应用于单目深度估计 (Issue #3)





 
Hi @chaoying0115 , thanks for your interest in our work!
 
We first lift features from 2D foundation models to 3D Gaussians. Then we use rendered features from 3D Gaussians to fine-tune 2D foundation models back. Depth estimation and semantic segmentation are just two downstream tasks we use to demonstrate the benefits of 3D-aware fine-tuning. Regarding depth estimation, we simply add a linear probing on top of the fine-tuned features.
 
Please see Sec. 3.3 for more details.
 
Note as we only fine-tuned the model on ScanNet++ (an indoor dataset), we found we still need to original 2D features to keep their generalization ability.

**Comment by ywyue** [comment]
Hi @chaoying0115 , there are two potential solutions:
1. When applied on KITTI, you could concatenate the original 2D features with our fine-tuned features.
2. Use our pipeline to finetune the 2D model on KITTI or other outdoor datasets.

Hope that helps!
